package erp.uniaura.modules.processo.model;

// --- REQUERIMENTOS ACADÊMICOS QUE O ALUNO PODE ABRIR JUNTO À SECRETARIA ---
public enum TipoProcesso {
    TRANCAMENTO_MATRICULA,
    REABERTURA_MATRICULA,
    TRANSFERENCIA_CURSO,
    APROVEITAMENTO_DISCIPLINA,
    DISPENSA_DISCIPLINA,
    REVISAO_NOTA,
    SEGUNDA_CHAMADA_PROVA,
    DECLARACAO_MATRICULA,
    HISTORICO_ESCOLAR,
    COLACAO_GRAU,
    OUTROS
}
